name: kareem_store
description: "Kareem Store App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar:
  firebase_core:
  cloud_firestore:
  intl: ^0.17.0
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.40.0
  flutter_screenutil: ^5.0.0+2
  pdf: ^3.6.0
  shared_preferences: ^2.3.0
  file_picker:
  path_provider: ^2.0.11
  image_picker:
  uuid:
  dropdown_search:
  share_plus: ^7.1.0
  open_filex: ^4.3.2
  permission_handler:
  screenshot:
  firebase_storage:
  hive: ^2.2.3
  print_bluetooth_thermal: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/tools_7307974.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Amiri
       fonts:
         - asset: fonts/Amiri-Regular.ttf
         - asset: fonts/Amiri-Bold.ttf
     - family: cairo
       fonts:
         - asset: fonts/Cairo-Medium.ttf
