import '../local_db/hive_init.dart';
import '../local_db/hive_safe_value.dart';
import '../local_db/models/client_local.dart';
import 'invoice_number_utils.dart';

/// An immutable operation ledger. Legacy balances are carried forward, not
/// silently repaired from an incomplete cloud/cache history on reconnect.
class CustomerBalanceStore {
  static String baseKey(String id) => 'customerBalanceBase:$id';
  static String eventKey(String id, String operationId) =>
      'customerBalanceEvent:$id:$operationId';

  static bool hasBase(String id) => appMetaBox.containsKey(baseKey(id));

  static double balance(String id, {double fallback = 0}) {
    if (!hasBase(id)) return fallback;
    var result = invoiceNum(appMetaBox.get(baseKey(id)));
    for (final key in appMetaBox.keys) {
      if (key.toString().startsWith('customerBalanceEvent:$id:')) {
        result += invoiceNum((appMetaBox.get(key) as Map)['delta']);
      }
    }
    return result;
  }

  /// Calculate a customer list in one pass over the stored events. Calling
  /// [balance] for each customer would rescan the whole metadata box each time.
  static Map<String, double> balancesForClients(Iterable<ClientLocal> clients) {
    final result = <String, double>{};
    final withBase = <String>{};
    for (final client in clients) {
      if (hasBase(client.id)) {
        withBase.add(client.id);
        result[client.id] = invoiceNum(appMetaBox.get(baseKey(client.id)));
      } else {
        result[client.id] = client.balance;
      }
    }
    const prefix = 'customerBalanceEvent:';
    for (final key in appMetaBox.keys) {
      if (key is! String || !key.startsWith(prefix)) continue;
      // Operation IDs generated by this app are UUIDs. The last separator
      // permits colons in an existing customer document ID.
      final separator = key.lastIndexOf(':');
      if (separator <= prefix.length) continue;
      final clientId = key.substring(prefix.length, separator);
      if (!withBase.contains(clientId)) continue;
      result[clientId] =
          result[clientId]! + invoiceNum((appMetaBox.get(key) as Map)['delta']);
    }
    return result;
  }

  static Future<void> preserveExistingBalances() async {
    final clients = clientsBox.values.toList();
    final accepted = balancesForClients(clients);
    final missingBases = <String, dynamic>{};
    final mirrors = <dynamic, ClientLocal>{};
    for (final client in clients) {
      if (!hasBase(client.id)) {
        missingBases[baseKey(client.id)] = client.balance;
      } else if (client.balance != accepted[client.id]) {
        // Restore a mirror interrupted after an imported event was flushed.
        // The accepted ledger itself is unchanged.
        client.balance = accepted[client.id]!;
        mirrors[client.id] = client;
      }
    }
    if (missingBases.isNotEmpty) {
      await appMetaBox.putAll(missingBases);
      await appMetaBox.flush();
    }
    if (mirrors.isNotEmpty) {
      await clientsBox.putAll(mirrors);
      await clientsBox.flush();
    }
  }

  /// Called only for a newly downloaded client. Modern documents expose the
  /// pre-operation baseline so importing their receipts cannot double count.
  static Future<void> initializeFromCloud(
      String id, Map<String, dynamic> data) async {
    if (hasBase(id)) return;
    await appMetaBox.put(baseKey(id),
        invoiceNum(data['financialBaseBalance'] ?? data['balance']));
    await appMetaBox.flush();
    final deferredPrefix = 'deferredCustomerEvent:$id:';
    for (final key in appMetaBox.keys.toList()) {
      if (key.toString().startsWith(deferredPrefix)) {
        await importEvent(id, key.toString().substring(deferredPrefix.length),
            Map<String, dynamic>.from(appMetaBox.get(key) as Map));
        await appMetaBox.delete(key);
      }
    }
  }

  static Future<void> importEvent(
      String id, String operationId, Map<String, dynamic> data) async {
    final safeData = hiveSafeMap(data);
    if (!hasBase(id)) {
      await appMetaBox.put('deferredCustomerEvent:$id:$operationId', safeData);
      return;
    }
    final key = eventKey(id, operationId);
    if (appMetaBox.containsKey(key)) return;
    await appMetaBox.put(key, safeData);
    await appMetaBox.flush();
    final client = clientsBox.get(id);
    if (client != null) {
      client.balance = balance(id);
      await client.save();
    }
  }
}
