// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrORj7qXhYtDOJarJXXyEnLGl2Uvro-1k',
    appId: '1:739436951854:web:d9a6623fe55607da6522bf',
    messagingSenderId: '739436951854',
    projectId: 'kareem-hammad',
    authDomain: 'kareem-hammad.firebaseapp.com',
    storageBucket: 'kareem-hammad.firebasestorage.app',
    measurementId: 'G-F1P6JQSH7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVLByU3ZYomy6WVsUDZStq1-Np2297N9Y',
    appId: '1:739436951854:android:8db7a3fe0c2fcfee6522bf',
    messagingSenderId: '739436951854',
    projectId: 'kareem-hammad',
    storageBucket: 'kareem-hammad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUcuZb4nW14LH38fuh6y1NPCJQWxLW_E',
    appId: '1:739436951854:ios:42c8cc5796dc4c2e6522bf',
    messagingSenderId: '739436951854',
    projectId: 'kareem-hammad',
    storageBucket: 'kareem-hammad.firebasestorage.app',
    iosBundleId: 'com.kareemham.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUcuZb4nW14LH38fuh6y1NPCJQWxLW_E',
    appId: '1:739436951854:ios:42c8cc5796dc4c2e6522bf',
    messagingSenderId: '739436951854',
    projectId: 'kareem-hammad',
    storageBucket: 'kareem-hammad.firebasestorage.app',
    iosBundleId: 'com.kareemham.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrORj7qXhYtDOJarJXXyEnLGl2Uvro-1k',
    appId: '1:739436951854:web:c265a9c7e6de513a6522bf',
    messagingSenderId: '739436951854',
    projectId: 'kareem-hammad',
    authDomain: 'kareem-hammad.firebaseapp.com',
    storageBucket: 'kareem-hammad.firebasestorage.app',
    measurementId: 'G-BYV8910YXT',
  );

}