// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXPnmpbOfnJQnvFmlCrb5a5GhUqg9opE',
    appId: '1:679011368192:web:9f901e76f7c65d1fadc7e5',
    messagingSenderId: '679011368192',
    projectId: 'saudi-database',
    authDomain: 'saudi-database.firebaseapp.com',
    storageBucket: 'saudi-database.firebasestorage.app',
    measurementId: 'G-Q1TH2C7QTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtpZvoo4K9HB80X50A2p9NRLtyB9NcB60',
    appId: '1:679011368192:android:a147c97613370eaaadc7e5',
    messagingSenderId: '679011368192',
    projectId: 'saudi-database',
    storageBucket: 'saudi-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mHTAPzLsM-B0x4CQ30VQpXxa2vLv6wM',
    appId: '1:679011368192:ios:45d0cca6382e17aaadc7e5',
    messagingSenderId: '679011368192',
    projectId: 'saudi-database',
    storageBucket: 'saudi-database.firebasestorage.app',
    iosBundleId: 'com.example.saudiDataIsGoldenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mHTAPzLsM-B0x4CQ30VQpXxa2vLv6wM',
    appId: '1:679011368192:ios:5bd6d842b09d6919adc7e5',
    messagingSenderId: '679011368192',
    projectId: 'saudi-database',
    storageBucket: 'saudi-database.firebasestorage.app',
    iosBundleId: 'com.example.saudiDataIsGoldenApp.RunnerTests',
  );
}
