import 'package:hive_flutter/hive_flutter.dart';
import 'models/product_local.dart';
import 'models/client_local.dart';
import 'models/supplier_local.dart';
import 'models/sync_queue_item.dart';

/// Box names — use these constants everywhere to avoid typos.
class HiveBoxNames {
  static const String products = 'products_cache';
  static const String clients = 'clients_cache';
  static const String suppliers = 'suppliers_cache';
  static const String syncQueue = 'sync_queue';
  static const String appMeta = 'app_meta'; // Stores lastSyncTimestamp, etc.
}

/// Keys for the appMeta box.
class HiveMetaKeys {
  static const String lastProductSyncAt = 'lastProductSyncAt';
  static const String lastClientSyncAt = 'lastClientSyncAt';
  static const String lastSupplierSyncAt = 'lastSupplierSyncAt';
}

/// Initializes and registers all Hive adapters.
/// Call this once from [main()] before [runApp()].
Future<void> initHive() async {
  await Hive.initFlutter();

  // Register TypeAdapters (generated by hive_generator via build_runner)
  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(ProductLocalAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(ClientLocalAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(SupplierLocalAdapter());
  if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(SyncQueueItemAdapter());

  // Open all boxes on startup safely (handles corrupted cache or schema upgrades)
  await _openBoxSafely<ProductLocal>(HiveBoxNames.products);
  await _openBoxSafely<ClientLocal>(HiveBoxNames.clients);
  await _openBoxSafely<SupplierLocal>(HiveBoxNames.suppliers);
  await _openBoxSafely<SyncQueueItem>(HiveBoxNames.syncQueue);
  await _openBoxSafely(HiveBoxNames.appMeta);
}

/// Opens a Hive box safely. If corrupted or schema changed, clears disk cache and re-opens.
Future<Box<T>> _openBoxSafely<T>(String name) async {
  try {
    return await Hive.openBox<T>(name);
  } catch (e) {
    try {
      await Hive.deleteBoxFromDisk(name);
    } catch (_) {}
    return await Hive.openBox<T>(name);
  }
}

/// Convenience accessors — use these to get open boxes from anywhere.
Box<ProductLocal> get productsBox {
  _ensureBoxOpen(HiveBoxNames.products);
  return Hive.box<ProductLocal>(HiveBoxNames.products);
}

Box<ClientLocal> get clientsBox {
  _ensureBoxOpen(HiveBoxNames.clients);
  return Hive.box<ClientLocal>(HiveBoxNames.clients);
}

Box<SupplierLocal> get suppliersBox {
  _ensureBoxOpen(HiveBoxNames.suppliers);
  return Hive.box<SupplierLocal>(HiveBoxNames.suppliers);
}

Box<SyncQueueItem> get syncQueueBox {
  _ensureBoxOpen(HiveBoxNames.syncQueue);
  return Hive.box<SyncQueueItem>(HiveBoxNames.syncQueue);
}

Box get appMetaBox {
  _ensureBoxOpen(HiveBoxNames.appMeta);
  return Hive.box(HiveBoxNames.appMeta);
}

void _ensureBoxOpen(String name) {
  if (!Hive.isBoxOpen(name)) {
    throw HiveError(
      'Hive box "$name" is not open yet. Make sure `await initHive();` is called before accessing database boxes.',
    );
  }
}
